# Xforge pretraining setup
{
  "hostfile": "logs/xforge/xforge-s/hostfile",
  "save": "logs/xforge/xforge-s/checkpoints",
  "load": "logs/xforge/xforge-s/checkpoints",
   "use_tutel": true,
   "moe_type": "megablocks",
   "moe_token_dropping": false,
   "moe_num_experts": 8,
   "expert_interval": 2,
   "enable_expert_tensor_parallelism": true,
   "model_parallel_size": 1,
   "context_parallel_size": 8,
   "moe_expert_parallel_size": 8,
   "moe_top_k": 1, 
   "make_vocab_size_divisible_by": 1,

   # model settings
   "num_layers": 16,
   "hidden_size": 4096,
   "intermediate_size": 14336,
   "num_kv_heads": 8,
   "num_attention_heads": 32,
   "seq_length": 65536,
   "max_position_embeddings": 65536,
  
  "norm": "rmsnorm",
  "rms_norm_epsilon": 1.0e-5,
  "pos_emb": "rotary",
  "rotary_pct": 1,
  "rotary_emb_base": 500000,
  "rope_fusion": false,
   "no_weight_tying": true,
   "gpt_j_residual": false,
   "output_layer_parallelism": "column",
   "attention_config": [[["ring"], 16]],
   
   "scaled_upper_triang_masked_softmax_fusion": false,
   "bias_gelu_fusion": false,
   "rope_fusion": false,
   "layernorm_fusion": false,

   # init methods
   "init_method": "small_init",
   "output_layer_init_method": "wang_init",

   # optimizer settings
   "optimizer": {
     "type": "Lamb",
     "params": {
       "lr": 0.008,
       "betas": [0.9, 0.999],
       "eps": 1.0e-8,
     }
   },
   "min_lr": 0.0008,

   # for all zero_optimization options, see https://www.deepspeed.ai/docs/config-json/#zero-optimizations-for-fp16-training
   "zero_optimization": {
    "stage": 0,
    "allgather_partitions": True,
    "overlap_comm": True,
    "reduce_scatter": True,
    "contiguous_gradients": True,
  },

   # batch / data settings
   "train_micro_batch_size_per_gpu": 1,
   "data_impl": "mmap",

   # activation checkpointing
   "checkpoint_activations": false,
   "checkpoint_num_layers": 1,
   "partition_activations": true,
   "synchronize_each_layer": true,

   # regularization
   "gradient_clipping": 1.0,
   "weight_decay": 0.1,
   "hidden_dropout": 0,
   "attention_dropout": 0,

   "precision": "bfloat16",
   # precision settings
   "bf16": {
     "bf16": true,
     "enabled": true,
     "loss_scale": 0,
     "loss_scale_window": 1000,
     "hysteresis": 2,
     "min_loss_scale": 1
   },

   # misc. training settings
   "train_iters": 47000,
   "lr_decay_iters": 47000,
   "distributed_backend": "nccl",
   "lr_decay_style": "cosine",
   "warmup": 0.01,
   "checkpoint_factor": 50,
   "eval_interval": 100,
   "eval_iters": 1,

   # logging
   "log_interval": 1,
   "steps_per_print": 1,
   "keep_last_n_checkpoints": 4,
   "wall_clock_breakdown": true,
}
