{
   "tokenizer_type": "HFTokenizer",

   "data_path": "/lustre/orion/gen243/world-shared/bbhusal/FORGE_TRAINING/dataset/all_text_document",
   "vocab_file": "/lustre/orion/gen243/world-shared/bbhusal/FORGE_TRAINING/dataset/all_vocab.json",

   "hostfile": "logs/forge-l/hostfile",

   # "pipe-parallel-size": 0,
   "model_parallel_size":4,

   # batch / data settings
   "train_micro_batch_size_per_gpu": 16,
   "gradient_accumulation_steps": 1,

   "data_impl": "mmap",
   # "split": "969,30,1",

   #aws-rccl workaround
   "num_workers": 1,

   # model settings
   "num_layers": 48,
   "hidden_size": 6144,
   "num_attention_heads": 48,
   "seq_length": 2048,
   "max_position_embeddings": 2048,
   "norm": "layernorm",
   "pos_emb": "rotary",
   "no_weight_tying": true,
   "gpt_j_residual": false,
   "output_layer_parallelism": "column",

   # these should provide some speedup but takes a while to build, set to true if desired
   "scaled_upper_triang_masked_softmax_fusion": true,
   "bias_gelu_fusion": true,

   # init methods
   "init_method": "small_init",
   "output_layer_init_method": "wang_init",

   # optimizer settings
   "optimizer": {
     "type": "LAMB",
     "params": {
       "lr": 0.006,
       "betas": [0.9, 0.999],
       "eps": 1.0e-8,
     }
   },

   "zero_allow_untested_optimizer": true,

   "min_lr": 0.00006,

   # for all zero_optimization options, see https://www.deepspeed.ai/docs/config-json/#zero-optimizations-for-fp16-training
   "zero_optimization": {
    "stage": 1,
    "allgather_partitions": True,
    "allgather_bucket_size": 450000000,
    "overlap_comm": True,
    "reduce_scatter": True,
    "reduce_bucket_size": 450000000,
    "contiguous_gradients": True,
   },


   "flops_profiler": {
      "enabled": true,
      "profile_step": 1,
      "module_depth": -1,
      "top_modules": 1,
      "detailed": true,
      "output_file": "flops.log",
   },

   "bf16":{
      "enabled": True,
   },

   # activation checkpointing
   "checkpoint_activations": true,
   "checkpoint_num_layers": 1,
   "partition_activations": true,
   "synchronize_each_layer": true,
   
   # regularization
   "gradient_clipping": 1.0,
   "weight_decay": 0.1,
   "hidden_dropout": 0,
   "attention_dropout": 0,


   # misc. training settings
   "train_iters": 10,
   "lr_decay_iters":10,
   "distributed_backend": "nccl",
   "lr_decay_style": "cosine",
   "warmup": 0.01,
   "checkpoint_factor": 50,
   "eval_interval": 300,
   "eval_iters": 5,

   # logging
   "log_interval": 5,
   "steps_per_print": 5,
   "keep_last_n_checkpoints": 200,
   "wall_clock_breakdown": true,

   "tensorboard_dir": "tensorboard",
   "log_dir": "logs",

   "deepspeed_mpi": True,
   "launcher": "slurm",
}
