{
   "data-path": "/lustre/orion/gen243/proj-shared/forge_dataset/tokens/all_text_document",
   "vocab-file": "/lustre/orion/gen243/proj-shared/forge_dataset/tokens/all_vocab.json",

   "train-iters": 20,
   "lr-decay-iters": 20,

   "eval-interval": 10, # After every n iterations, perform a evaluation step.
   "eval-iters": 10,    # Num of batches the evaluation will be performed on.

   "tensorboard-dir": "tensorboard",
   "log-dir": "logs",
   "use_wandb": False,

   "deepspeed_mpi": True,
   "launcher": "slurm",

   # logging
   "log-interval": 2,    # After every n step, it will log data to tensorboard
   "steps_per_print": 5, # After every n step, it will print the logs: (report includes the number of training steps, number of skipped optimizer updates (likely due to overflows in mixed-precision training), current learning rate, and current momentum.)

   "keep-last-n-checkpoints": 200,
   "wall_clock_breakdown": true, # Enable timing of the latency of forward/backward/update training phases.

   "flops_profiler": {
    "enabled": true,
    "profile_step": 10,
    "module_depth": -1,
    "top_modules": 5,
    "detailed": true,
    "output_file": "flopslog"
   },

  # Enable saving and loading checkpoints
  #"save": "checkpoints",
  #"load": "checkpoints",
  #"checkpoint_validation_with_forward_pass": False,
}
